name: .NET Core Desktop

on:
  push:
    branches: [ "master" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name: Src\SourceGrid.sln
      Test_Project_Path: Src\SourceGrid.Tests\SourceGrid.Tests.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    # Add MSBuild to the PATH
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    # Restore the application to populate the obj folder with RuntimeIdentifiers
    - name: Restore the application
      run: msbuild $env:Solution_Name /t:Restore /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}

    # Build the solution
    - name: Build the solution
      run: msbuild $env:Solution_Name /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}

    # Upload build artifacts
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4  # v3 yerine v4
      with:
        name: Build-${{ matrix.configuration }}
        path: |
          **/bin/${{ matrix.configuration }}/
          **/obj/${{ matrix.configuration }}/

  publish-nuget:
    needs: build
    # if: startsWith(github.ref, 'refs/tags/v')
    runs-on: windows-latest
  
    env:
      Solution_Name: Src\SourceGrid.sln

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    # Add MSBuild to the PATH
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    # Restore dependencies
    - name: Restore the application
      run: msbuild $env:Solution_Name /t:Restore /p:Configuration=Release

    # Pack the NuGet package
    - name: Pack NuGet package
      run: dotnet pack $env:Solution_Name --configuration Release --no-restore --output ../nupkg

    # Check generated packages
    - name: Check generated packages
      run: |
        Write-Host "Contents of nupkg directory:"
        Get-ChildItem "../nupkg/" -Force

    # Push to NuGet.org
    - name: Push to NuGet.org
      run: dotnet nuget push "../nupkg/SourceGrid-mehmetulukaya.*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate


