name: Build and Publish

on:
  push:
    branches:
      - master
    paths:
      - 'Src/**'

jobs:
  build-and-publish:
    runs-on: windows-latest  # Windows ortamÄ±

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET 10
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Check directory structure
      run: |
        pwd
        ls -la
        echo "Contents of Src directory:"
        ls -la Src/

    - name: Restore dependencies
      run: dotnet restore
      working-directory: Src

    - name: Build and Pack
      run: dotnet pack --configuration Release --no-restore --output ../nupkg
      working-directory: Src

    - name: Push to NuGet.org
      run: |
        dotnet nuget push "./nupkg/*.nupkg" `
          --api-key ${{ secrets.NUGET_API_KEY }} `
          --source https://api.nuget.org/v3/index.json `
          --skip-duplicate

